In [29]:
import numpy as np

a = np.matrix(np.arange(12).reshape(3, 4))
print(a)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

a_del = np.delete(a, [1,2], 0)
print(a_del)
# [[ 0  1  2  3]
#  [ 8  9 10 11]]

print(a)
print(np.reshape(a,(-1,2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [25]:
a = np.matrix(np.arange(12).reshape(6,2))
print(a)
b = np.insert(a,[2],np.arange(100,106).reshape(6,1),axis=1)
b = b.reshape((18,))
print(b)
np.insert(b,1,np.zeros(b.shape[0]*b.shape[1],),axis=0).transpose()

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[  0   1 100   2   3 101   4   5 102   6   7 103   8   9 104  10  11 105]]


matrix([[  0,   0],
        [  1,   0],
        [100,   0],
        [  2,   0],
        [  3,   0],
        [101,   0],
        [  4,   0],
        [  5,   0],
        [102,   0],
        [  6,   0],
        [  7,   0],
        [103,   0],
        [  8,   0],
        [  9,   0],
        [104,   0],
        [ 10,   0],
        [ 11,   0],
        [105,   0]])

In [35]:
a = np.zeros([12,])
idx = np.arange(0,len(a),3)
a[idx]=1
print(a)
np.append(a,np.zeros(10,))

[1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0.]


array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])