In [3]:
from shapely.ops import nearest_points
from shapely import Point,Polygon
from shapely import MultiPolygon

b= Point(1.0,1.0)
print(b)

pts = [Point(3,3),Point(0.5,-1),Point(-1,-1)]
triangle = Polygon([(0, 0), (1, 0), (0.5, 1), (0, 0)])
triangle2 = Polygon([(1, 4), (2, 4), (1.5, 5), (1, 4)])
# t = MultiPolygon([triangle,triangle2])
a = list(nearest_points(triangle, pts))
print(a)
print(a[0][0].x)

POINT (1 1)
[array([<POINT (0.5 1)>, <POINT (0.5 0)>, <POINT (0 0)>], dtype=object), array([<POINT (3 3)>, <POINT (0.5 -1)>, <POINT (-1 -1)>], dtype=object)]
0.5


In [38]:
import numpy as np
a = np.linspace(10,1,10)
print(a)
b=a[0::2]
print(b)

[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[10.  8.  6.  4.  2.]


In [40]:
class Node:
    def __init__(self,i,parent=None):
        self.i=i
        self.parent = parent
        self.children=[]
        if parent is not None:
            parent.children.append(self)
            
p0 = Node(0)

p11 = Node(11,p0)
p12 = Node(12,p0)

p21 = Node(21,p11)
p22 = Node(22,p11)

p32 = Node(32,p22)

p = p32
while p is not None:
    print(p.i)
    p = p.parent
    
        

32
22
11
0


In [26]:
import casadi as ca
a = ca.DM([[1,2],[3,4],[5,6]])
ca.sum2(a*a)


DM([5, 25, 61])

In [35]:
a = np.zeros([12,])
idx = np.arange(0,len(a),3)
a[idx]=1
print(a)
np.append(a,np.zeros(10,))

[1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0.]


array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])